### PR TITLE
Translate spanish docker

### PR DESCRIPTION
**Pull request by manuelver**
Spanish translation of Docker training md files from /formacion/cursos/docker/ folder to /formacion/cursos/docker/ES/ except configuration pages and web elements.

May contain some corrections in the source folder /formacion/cursos/docker/.
Spanish translation of Docker training md files from /formacion/cursos/docker/ folder to /formacion/cursos/docker/ES/ except configuration pages and web elements.

### CODE REVIEW

**Review by alambike — COMMENTED** [review]
@manuelver could you test if the new ES folder is working with docsify?
I think it need some configuration, and maybe the ES folder should be in lowercase :thinking: ?

image

**Comment by alambike** [comment]
> @alambike It seems that yes, it can be solved with an alias and the folder must be lowercase. 
> 
> Now you would also have to think about how it is displayed in the UI. It may be as the link indicates, with a fallbackLanguages: 

Yes please, configure those options in the docsify config file and we could merge this ASAP!

**Comment by manuelver** [comment]
> > @alambike It seems that yes, it can be solved with an alias and the folder must be lowercase.
> > Now you would also have to think about how it is displayed in the UI. It may be as the link indicates, with a fallbackLanguages:
> 
> Yes please, configure those options in the docsify config file and we could merge this @manuelver !

I've had some trouble with github that I may have fixed on the wild side. Now I think it's all ok. 

It should look like this: 
imatge

imatge

**Comment by alambike** [comment]
I think the selector is a bit misleading, looking at the images seems that the selected language is not what is showing 😅

**Comment by manuelver** [comment]
> I think the selector is a bit misleading, looking at the images seems that the selected language is not what is showing sweat_smile

@alambike I change the button text in Galician to "Cambiar a castellano" and in Spanish to "Cambiar ao Galego".

**Review by alambike — APPROVED** [review]

**Pull request merged**
